language: node_js
sudo: false
env:
  - CXX=g++-5
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
node_js:
  - "node"
after_script: npm run coverage && npm run coveralls