environment:
    matrix:
        - nodejs_version: "5.6"
install:
    - ps: Install-Product node $env:nodejs_version
    - npm install
test_script:
    - node --version
    - npm --version
    - npm test
version: "{build}"
build: off